### ISSUE TITLE
Synchronous mode

### ISSUE THREAD

**Issue by gregberge** [svg/svgo#1015]
I am the author of [SVGR](https://github.com/smooth-code/svgr), a library to transform SVG into React Components. It offers build in support of SVGO.

SVGR can be run only in asynchronous mode today. But tomorrow we would like to be able to run it synchronously. It opens new possibility, like a Babel plugin for an example.

I would like to know if synchronous mode is an option for SVGO?

**Comment by lencioni** [comment]
We are using an older version of svgo that works synchronously in [a babel plugin](https://github.com/airbnb/babel-plugin-inline-react-svg), but we are getting a lot of people asking to update to a newer version because of a CVE ([example](https://github.com/airbnb/babel-plugin-inline-react-svg/pull/35)). We are unable to update because the newer version cannot be used synchronously.

@GreLI would you be open to exposing a method like `optimizeSync` from this package?

**Comment by ljharb** [comment]
ping @GreLI

**Comment by remy90** [comment]
I've noticed some issues have auto issue closing bots, so consider this a wordy bump/+1

**Comment by TrySound** [comment]
API is synchronous in v2

**Comment by ljharb** [comment]
@TrySound thank you!

**Comment by ljharb** [comment]
@TrySound it looks like `require('svgo')` requires `.default` - it's usually a really bad idea to expose babel/ts interop implementation details. in other words, the `module.exports` value should be directly usable.
