### ISSUE TITLE
svgo remove transform="rotate(0)"

### ISSUE THREAD

**Issue by alexander-akait** [svg/svgo#1035]
Input:
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 230 230" transform="rotate(0)">
<polygon fill-opacity="1" stroke="#000" fill="#000" stroke-width="70" stroke-linejoin="round" points="77,180.9 153,180.9 191.1,115 153,49.1 77,49.1 38.9,115 "/>
</svg>
```

Output:
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 230 230">
<path stroke="rgba(55, 55, 55, 0.5)" fill="rgba(55, 55, 55, 0.5)" stroke-width="70" stroke-linejoin="round" d="M77 180.9h76l38.1-65.9L153 49.1H77L38.9 115z"/>
</svg>
```

It is expected? Looks like the bug. Original issue https://github.com/cssnano/cssnano/issues/593

**Comment by GreLI** [comment]
`rotate(0)` is equal to `matrix(1 0 0 1 0 0)` which does nothing. One can disable `removeUseless` of `convertTransform` plugin to prevent removing.

**Comment by evilebottnawi** [comment]
@GreLI Why it is enable by default? Looks it is not safe optimization

**Comment by GreLI** [comment]
Depends on what do you mean by “safe”. SVGO’s main purpose is optimizing images for web, so it has some optimizations that could be considered “unsafe” under other circumstances. Since SVGO has wide usage it’s highly configurable for anyone’s needs. But there is also a tradeof between optimization level and lossiness. One can say that SVGO is lossy tool, but that’s because of it is best balance most cases. Transform that doing nothing isn’t needed in 99%, so it’s being removed.
