### ISSUE TITLE
What options can change to hid prefix class of svg file?

### ISSUE THREAD

**Issue by TongDaDa** [svg/svgo#1062]
<img width="387" alt="2018-11-29 11 50 13" src="https://user-images.githubusercontent.com/23241188/49198240-24708800-f3cd-11e8-9a2c-8a12b60ee150.png">

The className of text tag has named `virtualBox_TextInSvg`, but it carry a prefix that is filename after outputed, What should I do?

I want to keep the same classname in svgfile

![2018-11-29 11 49 45](https://user-images.githubusercontent.com/23241188/49198242-24708800-f3cd-11e8-87f6-6e1b1e53d998.png)

**Comment by strarsis** [comment]
`svgo --disable=prefixIds` should disable the prefixIds plugin that prefixes IDs + classes.

**Comment by valkko** [comment]
Is there a way to _only_ prefix IDs, but not classes? I have a case where the classes should stay as is, but IDs prefixed to avoid conflicts.

Since the config option is named `prefixIds` you'd think it would only affect IDs in the first place.

**Comment by litinskii** [comment]
How to use prefix only for class ?

**Comment by strarsis** [comment]
@litinskii: Hm, this would probably require code changes in the `prefixIds` plugin.
Only one method would have to be called then, `addPrefixToClassAttr`(https://github.com/svg/svgo/blob/master/plugins/prefixIds.js#L212).

**Comment by litinskii** [comment]
@strarsis Thanks for answer. I'm asking this, because I'm trying to migrate from https://github.com/jkphl/svg-sprite, and there was an option like 
![image](https://user-images.githubusercontent.com/10028441/57966846-38e71380-7960-11e9-9aae-c2d2e3e4261a.png)
(https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md)

and it was very useful, I mean allow to specify if you want to add namespace only for class for example. 

I thinks it would be cool if we have some king of options for prefixIds plugin. @strarsis What you think about this ?

**Comment by strarsis** [comment]
@litinskii: You can try the PR here: https://github.com/svg/svgo/pull/1106

**Comment by litinskii** [comment]
@strarsis Thanks will try.

**Comment by litinskii** [comment]
@strarsis seems it work for my case. Thanks.
