### ISSUE TITLE
Retain unused classes in style element

### ISSUE THREAD

**Issue by Smilebags** [svg/svgo#1068]
I have created an SVG which has classes (which are used in the browser to style the SVG) but are not present on the SVG elements. SVGO seems to be stripping these classes away, which isn't very helpful. I've tried removing inlineStyles because apparently that deals with this, but it hasn't seemed to change anything.

Here's my source and result:
```
<svg id="menu-icon" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
<style>
    rect {
        transition: 0.2s;
        fill: #000000;
        fill-opacity: 0.2;
    }
    .active rect {
        fill-opacity: 0.4;
    }
</style>
    <rect x="9" y="19" width="82" height="7" rx="3.5" ry="3.5"/>
    <rect x="9" y="46" width="82" height="8" rx="3.5" ry="3.5"/>
    <rect x="9" y="73" width="82" height="7" rx="3.5" ry="3.5"/>
</svg>
```
Result un-minified for readability:
```
<svg id="menu-icon" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <style>
    rect{
      transition:.2s;fill:#000;fill-opacity:.2
    }
    </style>
  <rect x="9" y="19" width="82" height="7" rx="3.5" ry="3.5"/>
  <rect x="9" y="46" width="82" height="8" rx="3.5" ry="3.5"/>
  <rect x="9" y="73" width="82" height="7" rx="3.5" ry="3.5"/>
</svg>
```
As you can see, `.active rect` styles have disappeared. Any idea how to retain them?

**Comment by strarsis** [comment]
@Smilebags: The [inlineStyles plugin](https://github.com/svg/svgo/blob/master/plugins/inlineStyles.js) removes selectors and styles that matched, 
the plugin can be disabled, or just its cleanup step (but this makes less sense usually) see the [`removeMatchedSelectors`](https://github.com/svg/svgo/blob/master/plugins/inlineStyles.js#L9) option which is enabled by default.

**Comment by SethFalco** [comment]
SVGO treats SVGs as self-sufficient rather than part of a larger document. If the SVG will be inlined in a larger document, then you'd need to customize the config to match your use case.

In this case, you'd want to disable `minifyStyles` which removes the selectors unused in the SVG itself.

You can pass the following options to SVGO either through the JavaScript API, or by making a file called `svgo.config.js` in the current working directory.

**`svgo.config.js`**
```js
module.exports = {
  plugins: [
    {
      name: "preset-default",
      params: {
        overrides: {
          minifyStyles: false
        }
      }
    }
  ]
}
```

If you're inlining anyway, I'd also recommend enabling the `removeXMLNS` and `removeXlink` options, which are disabled by default but perfectly safe when inlining SVGs in an HTML document.


**`svgo.config.js`**
```js
module.exports = {
  plugins: [
    {
      name: "preset-default",
      params: {
        overrides: {
          minifyStyles: false
        }
      }
    },
    "removeXMLNS",
    "removeXlink"
  ]
}
```
