### ISSUE TITLE
`removeUnknownsAndDefaults` removes `mask-type` attribute

### ISSUE THREAD

**Issue by mendes5** [svg/svgo#1120]
Looks like the plugin removeUnknownsAndDefaults removes any unknown attributes aka: [anything not listed in attrsGroups](https://github.com/svg/svgo/blob/master/plugins/_collections.js).
The file links to the [SVG spec](http://www.w3.org/TR/SVG11/intro.html#Definitions), so I assume that the author got all attributes from there. The problem is that the `mask-type` attribute is actually defined in the [CSS Masking Module Level 1](https://www.w3.org/TR/css-masking-1/) spec in the [SVG Mask Sources](https://www.w3.org/TR/css-masking-1/#svg-masks) section.

So, there is any reason for this attribute not being listed as "known"? is this on purpose?

**Comment by GreLI** [comment]
Yeah, SVGO is mainly based on SVG 1.1, because it was where it started and all in place, you know. The property you refer is for SVG 2. It refers to different CSS modules. I've added some new properties from it (and even removed some which didn't make it there), but haven't checked thoroughly, so I must have missed it.

SVG 2 is CR currently but AFAIK not all its features are supported in browsers or anywhere. So, it just new properties which have to be added.

**Comment by paulschreiber** [comment]
I hit this problem today. `mask-type="alpha" ` was being stripped unexpectedly.

**Comment by XhmikosR** [comment]
@TrySound isn't this fixed by https://github.com/svg/svgo/commit/4490d62ee9f83febeb18f4a83a297c544459514a?

**Comment by TrySound** [comment]
Right
