### ISSUE TITLE
`reusePaths` incompatible with `multipass`, throws <Unbound namespace prefix: "xlink"> error

### ISSUE THREAD

**Issue by coreyward** [svg/svgo#1200]
Input SVG: 
```svg
<svg viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
  <g stroke="#000" fill="none">
    <path d="M25 25a7 7 0 11-14 0 7 7 0 0114 0z"/>
    <path d="M25 25a7 7 0 11-14 0 7 7 0 0114 0z"/>
  </g>
</svg>
```

Command:
```
svgo -i tmp.svg -o - --enable=reusePaths --multipass
```

Result:
> Error in parsing SVG: Unbound namespace prefix: "xlink"
Line: 0
Column: 189
Char: >

**Comment by JTBrinkmann** [comment]
Actually, reusePaths isn't just incompatible with --multipass, it results in outright invalid SVG because it doesn't add the xlink namespace. As a fix, reusePaths could add `xmlns:xlink="http://www.w3.org/1999/xlink"` to the root svg element (if any path is acutally reused). This way, it would also work with multipass.

**Comment by JTBrinkmann** [comment]
I implemented (and tested) both options, either one could be merged.
- [SVG 1.2 compatible fix](https://github.com/JTBrinkmann/svgo/tree/fix-reusePaths-svg1.2-compatible)
- [SVG 2 compatible fix](https://github.com/JTBrinkmann/svgo/tree/fix-reusePaths-svg2-compatible)

**Comment by TrySound** [comment]
Good catch! I'll fix it soon.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.6.0
