### ISSUE TITLE
Documentation with explanation and motivation

### ISSUE THREAD

**Issue by vanillajonathan** [svg/svgo#1460]
There is some brief documention in the "[Built-in plugins](https://github.com/svg/svgo#built-in-plugins)" chapter in the README file. But I would love to see a wiki page that explains each plugin and the motivation behind it and any possible backsides to it.

- removeXMLProcInst — Benefit is smaller file. Does this reduce XML compatibility?
- removeComments — Possible downsides is that it might strip out copyright information
- removeMetadata — Possible downsides is that it might strip out copyright information
- removeTitle — Does this decrease accessibility?
- removeDesc — Does this decrease accessibility?
- removeEditorsNSData — Downside is that if you reopen the file in editor then?
- removeHiddenElems — What is a hidden element? Oh, the source code says zero-sized elements.
- removeEmptyText — Possible downside if it has an `id` and content is set by JavaScript
- removeEmptyContainers — What is considered a container?
- cleanupEnableBackground — What is `enable-background` and why is it undesirable?
- convertStyleToAttrs — Why is this a good thing, and does it have any downsides?
- convertColors — Benefit is smaller file due to more compact notation. Does this do rgb**a**?
- convertPathData — Does this have any downsides?
- removeUnknownsAndDefaults — Downside might be if you use `ng-` attributes for Angular.
- removeUselessStrokeAndFill — What determines if they're classified as useless?
- prefixIds — What's the default delimiter? Oh, reading the source code I found out it is `__` double underscore.
- cleanupIDs — Downside is that might break external JavaScript that rely on those ids.
- cleanupNumericValues — Does this have any downside?
- moveElemsAttrsToGroup — Why is this desirable and is there any downside?
- collapseGroups — What determines if a group is classified as useless? 
- removeRasterImages — Benefit is smaller file size. Downside is that it can remove visual content.
- convertShapeToPath — Why is this good? Does it have any downsides?
- convertEllipseToCircle — Benefit is better semantics. Downside is that you can't reshape it with JavaScript?
- removeDimensions — What is the implications of this?
- removeStyleElement — Can this increase portability and compatibility? Downside is that it can break styling.
- removeScriptElement — Advantage is that it can increase security? Downside is that it can strip off interactivity.

Many of these upsides and possible downsides might not be obvious to everyone, some of the answers can be learnt from reading the source to each plugin.

**Comment by TrySound** [comment]
Yeah, the table can be replaced with something more descriptive.

Would you like to work on this? I don't really have all answers, we can discuss in discord though.

**Comment by vanillajonathan** [comment]
The table is quite good as it is, it is simple, if we want to explain the motivation behind each plugin and list all each its benefits and potential drawbacks it might become too much content for that table, so it would probably be better to keep the table in the README as it is, but create a wiki page that goes more in-depth.

I don't have the answers either, I was looking at the README and a bunch of questions popped up to which I had no answer to, hence I filed this issue.

You could probably answer some of these questions.

**Comment by GreLI** [comment]
Some comments are inside plugins themselves.

`removeXMLProcInst` — XML-proc is not required. No known issues about its absence.
`removeComments` — no, copyright information is usually in metadata. Thought might be a good addition to keep comments starting from “!” as it happens with JS libraries. I don't know though if anyone uses something like this.
`removeMetadata` — disable the plugin if you want keep copyright. Or PR with similar solution as above is welcome.
`removeTitle`, `removeDesc` — probably really decrease accessibility, however, it's not used that often.
`removeEditorsNSData` — suggested flow is to optimize after the editor, and keep source files separately. However, shouldn't be a problem until some non-standard editor extensions.
`removeHiddenElems` — removes `display:none` or `visibility:hidden` or zero-sized and thus non-rendering elements. May mess scripts though. Probably worth adding checking for `id` (marking that way that element is used) like in other plugins.
`removeEmptyText` same as above.
`removeEmptyContainers` — removes non-rendering things like empty `<g></g>`. Usually it's an after-editing garbage.
`cleanupEnableBackground` — removes `enable-background` because usually it does nothing. Just like many other cleanup.
`convertStyleToAttrs` — attrs take less bytes than `style="/*attrs*/"` when there are only few (usually it is so).
`convertColors` — `rgba` is relatively recent addition (more like SVG 2), so it's not used by SVGO. However, browsers support it (but not editors probably).
`convertPathData` — it has _a lot_, a whole world inside the plugin, including downsides. Kir wanted to split it long ago.
`removeUnknownsAndDefaults` — yeah, there already was in issue with `data-*` and `aria-*` attributes. (Now keep by default.)
`removeUselessStrokeAndFill` — if you don't have `stroke` and `fill` attributes (note that by default `fill` is black), corresponding `fill-*` and `stroke-*` attributes will have effect on nothing.
`prefixIds` — an optional plugin, which purpose to manage images in CI/CD environment.
`cleanupNumericValues` — since it rounds numbers, of course it can lead to distortions due to too strong rounding. Note, `path` data is handled by `convertPathData` plugin which does similar things as well. (Probably a subject to refactor.)
`moveElemsAttrsToGroup` — eliminates repeating by moving attrs like `fill="#deadbeef"` on every element to their parent group. (Doesn't create a group however, it could be an interesting optimization, but has a lot of hidden complexities.)
`collapseGroups` — replaces useless groups with their content. Useless means that they don't have any properties. Could be result of another optimization (like applying transformations) or garbage left after editing by an editor that don't care on internal structure. Note that `moveElemsAttrsToGroup` is purposely running before `collapseGroups`, so that groups with share attributes could stay.
`removeRasterImages` — raster filters often are bad effects which haven't been done by SVG methods. Adobe Illustrator is known to create this ones instead of SVG filters.
`convertShapeToPath` — `path` takes less bytes than `rect` or `polygon`.
`convertEllipseToCircle` — circle is a special case of ellipse and also takes less bytes, so if circle is expressed as an ellipse, it worth converting.
`removeDimensions` — many SVGs have both `viewBox` and dimensions (`width`/`height`), but depending on usage one don't need them both if they're equal. However, this plugin is lossy—you lose sizes when using SVG as an image (or background image), so it's disabled by default.
`removeStyleElement` — more like an image manipulation plugin to remove garbage or use with `inlineStyles` plugin.
`removeScriptElement` — SVG as an image already have disabled scripts in browsers by security reasons. One needs special handling of SVG to have it running with scripts.
