### ISSUE TITLE
License removed by default. Why?

### ISSUE THREAD

**Issue by toastal** [svg/svgo#1609]
**Describe the bug**
> SVG files, especially those exported from various editors, usually contain a lot of redundant and useless information.

How is the metadata, especially the license, considered "useless"? Some information might be, but I would assume authors want to retain their licenses.

**To Reproduce**
Run the default settings on any image with a `<metadata>` tag

**Expected behavior**
Some or all of the metadata is preserved or turned into specific options for `removeMetadata`.

**Desktop (please complete the following information):**
```console
$ svgo --version
2.7.0
$ node --version
v14.18.0
$ uname -omvprs
Linux 5.14.8-zen1 #1-NixOS ZEN SMP Tue Jan 1 00:00:00 UTC 1980 x86_64 unknown GNU/Linux
```

**Comment by TrySound** [comment]
`xmlns:cc` attribute is removed as unused after whole metadata is removed. What exactly do you expect to keep in metadata? Only `cc:License` with its content?

**Comment by toastal** [comment]
https://stackoverflow.com/questions/38775825/semantically-correct-way-to-add-a-copyright-notice-into-a-svg-file#answer-38882847

While not exactly the same as the CC namespace, this was the top web search result for how to put a license in an SVG file

**Comment by timegrinder** [comment]
I've also just noticed this on a bunch of SVG's I've been making (unfortunately I hadn't double-checked during the process as I thought it would be considered metadata and not editor data) and found this reported issue.

The attributes in `dc` fields would also be an optional candidate for keeping if requested as there's already 'Keep title' and 'keep description' options which unfortunately Illustrator and Inkscape don't use directly, all of that goes into what ends up considered 'editor data'.

The allow list would definitely be appreciated as personally the option to keep some accessibility / informational data is entirely necessary, even within an optimised image. This also covers issues that can arise when people are trying to honour creative commons licenses when editing SVG's that they still want to optimise.

Having the ability to 'keep x but optimise where appropriate' the `rdf` data would be great.

**Comment by TrySound** [comment]
I see we have a lot of not standartized attributes. Im not familiar with any of them. It would help it you specify a set of rules when its safe and when its not to delete attributes.

**Comment by toastal** [comment]
> not [standardized] attributes

```svg
<svg
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   ></svg>
```

Those namespace links link to the standards. I would say 99% of the time it's unsafe to delete them by default and could _maybe_ sometimes be manually removed (for instance, removing all of the attribution info but putting a link to that information elsewhere on a website to minimize the size of the file).

**Comment by timegrinder** [comment]
There's a list of broad standards for what attributes and elements are acceptable to use but both programs list the standards in a different structure, and the standards aren't applied evenly from one program to the next. Inkscape and Illustrator both have the same information stored in an entirely different tree and element structures (even to the point the same field is in two different element types) so we'll have to take a list of both of them at least.

The Inkscape version looks more bare and simplified vs the Illustrator one, so that's a start at least.

**Comment by GreLI** [comment]
@toastal XML is eXtensible format. What you refer is just identifiers of that extensions that someone did. It's not necessarily standard though, anyone involved can extend it in a such way. Well, RDF is known standard, but it has nothing specific with the license, at least that's how it represented here.

See also #431. You words “unsafe” have nothing in support. Please, don't mix your opinion with facts. SVGO just a tool, like knife or axe, and it is within users responsibility how to use it.

**Comment by timegrinder** [comment]
My mistake for not checking closed issues, and this is more of a feature request than a bug.

While the RDF extension isn't a small fixed standard, and the relevant data isn't stored the same way from one program to the next I'm sure we can break down the editor data cleaner into parts to choose to remove and keep+optimise the portions we want. The data definitely isn't stored optimally anyway, and the title/desc naturally have their own elements that don't need to be inside an `rdf` area and can be moved out.

I can definitely see why `rdf` gets cleaned out with the `EditorNS` - an example is Illustrator nests the `rdf` space inside the `x:xmpmeta` area. It places the details we're talking about inside an unneccesarily deep tree. It also doesn't even use the same RDF conventions as Inkscape does.

Amusingly I just noticed that 'keep metadata' will still keep the `<metadata/>` tag when empty despite it being useless (although, admittedly, I use SVGO through the SVGOMG which might not be a perfect replication of SVGO's workings).

What I would suggest is those who are interested in working on it bring together the list of rules that TrySound requested and also work out a more efficient method of keeping the details we want to keep that's compatible with various editor formats as there is **definitely** room to optimise that information if keeping it. 

An example being with license information - we do not need to keep anything more than the actual license name+link itself. Inkscape includes all of the extra license resource web links that are not needed since a user could just open the initial link and see all of those details for themselves. But this could end up included if we just blanketly permitted `cc` spaces.

**Comment by toastal** [comment]
I'm can't remark much on that. I've not opened Illustrator in like 10 years; my typical workflow is bouncing between Inkscape & Neovim. The Inkscape output seems reasonable though.

**Comment by toastal** [comment]
> Please, don't mix your opinion with facts. SVGO just a tool, like knife or axe, and it is within users responsibility how to use it.

@GreLI Flipped, how is it a "fact" that metadata is useless? As in the context of 

> SVG files, especially those exported from various editors, usually contain a lot of redundant and useless information.

I must've searched the wrong words to not have bumped #431 instead of opening a new bug, but I agree with that post that the this feels like opt-in instead of opt-out behavior.  Is it not actionable to separate license information from the _actual_ editor metadata? Currently opting out of the overly-broad `removeMetadata` to retain license information, means you get all of the editor metadata which is one of the primary reasons for using this tool. 

My use case was the retain the metadata for Inkscape in my source control for future editing while stripping the editor metadata but leaving the license information for using on the web.

**Comment by toastal** [comment]
My solution:

I moved to an Apache 2.0-licensed Python project called [`scour`](https://github.com/scour-project/scour). Metadata stripping is a non-default flag `--remove-metadata` which actually contains the help text of `remove <metadata> elements (which may contain license/author information etc.)` to caution users who opt into this flag.
