### ISSUE TITLE
Multi Core Usage

### ISSUE THREAD

**Issue by erfanmola** [svg/svgo#1694]
Hi, I was wondering if there is an option to take advantage of a MultiCore CPU by spreading a workload into separate workers
I have an SVG File which takes 20 Seconds to compress on i7-11370H CPU, it is using only one core of the CPU at a time

**Comment by SethFalco** [comment]
It's currently not possible to use multiple cores in any capacity.

In future, we'll likely use multiple cores when optimizing multiple images, such as a directory (https://github.com/svg/svgo/issues/1769). However, it's unlikely we'll support utilizing multiple cores to optimize a single image.

Any ideas or [PoCs](https://wikipedia.org/wiki/Proof_of_concept) would be welcome though if anyone can think of a practical and clean implementation where we can use multiple cores to optimize a single image.

**Comment by emansom** [comment]
> It's currently not possible to use multiple cores in any capacity.

[Wrong](https://nodejs.org/api/worker_threads.html#worker-threads). Been there since forever.

[Here](https://github.com/emansom/libdepixelize-wasm/blob/fe086801c857d31ccab33c3ee7f8ec0be52774df/src/pool.ts#L100-L117)'s a example of how the work could be split up:
```ts
export async function executeBatch(
  pool: WorkerPool,
  items: ImageDataLike[],
  options?: Partial<DepixelizeOptions> & BatchOptions,
): Promise<DepixelizeBatchResult> {
  if (items.length === 0) {
    return { results: [], totalTimeMs: 0 };
  }

  const { onProgress, maxConcurrency: _mc, maxMemoryMB: _mm, ...depixelizeOptions } =
    options ?? {};
  const start = performance.now();
  let completed = 0;

  const results = await Promise.all(
    items.map(async (item, _i) => {
      const pixels = new Uint8Array(item.data.buffer.slice(0));
      const fn = await pool.acquire();
      try {
        const result = await fn(pixels, item.width, item.height, depixelizeOptions);
        completed++;
        onProgress?.(completed, items.length);
        return result;
      } finally {
        pool.release(fn);
      }
    }),
  );

  return { results, totalTimeMs: performance.now() - start };
}

export function calculateConcurrency(
  items: ImageDataLike[],
  maxConcurrency: number,
  maxMemoryMB: number,
): number {
  if (items.length === 0) return 1;

  const maxImagePixels = Math.max(...items.map((item) => item.width * item.height));
  const peakMB = (maxImagePixels * 4 * OVERHEAD_FACTOR) / (1024 * 1024);
  const memoryPerWorker = WASM_BASE_MB + peakMB;
  const memoryLimit = Math.floor(maxMemoryMB / memoryPerWorker);

  const totalPixels = items.reduce((sum, item) => sum + item.width * item.height, 0);
  const estimatedMs = totalPixels * MS_PER_PIXEL;
  if (estimatedMs < STARTUP_MS * 2) return 1; // startup cost dominates

  return Math.max(1, Math.min(maxConcurrency, items.length, memoryLimit));
}
```

 [This](https://github.com/emansom/libdepixelize-wasm/blob/9695b874fda0c417de3aa210ddc037f8a8dbe0bf/test/unit/batch.test.ts#L73-L77) is then how to utilize it, works a treat and scales linearly with more cores:

```ts
const items = [
  createImageData(2, 2, () => [255, 0, 0, 255]),
  createImageData(2, 2, () => [0, 255, 0, 255]),
  createImageData(2, 2, () => [0, 0, 255, 255]),
];

const progressCalls: [number, number][] = [];
await depixelizeBatch(items, {
  onProgress: (completed, total) => {
    progressCalls.push([completed, total]);
  },
});
```

> Any ideas or [PoCs](https://wikipedia.org/wiki/Proof_of_concept) would be welcome though if anyone can think of a practical and clean implementation where we can use multiple cores to optimize a single image.

I opted to [optimize](https://github.com/emansom/libdepixelize-wasm/commit/9695b874fda0c417de3aa210ddc037f8a8dbe0bf) the SVG generation instead, but sure, I'll add it on my TODO.

**Comment by SethFalco** [comment]
Damn, pretty blunt. 😅 

Care to offer a few more words on what I said wrong? Looking back, I can see how my wording could be misconstrued.

In SVGO v3/v4, we do not expose any way to use multiple cores.

Yes, I'm aware of worker threads. However, this issue is regarding the use of multiple cores for a **_single_** SVG, not across multiple SVGs.

My comment was not referring to a technical limitation in hardware or Node.js, but rather an architecture limitation with how SVGO processes SVGs.

Processing multiple SVGs in parallel would be simple enough to do. As for taking advantage of multiple cores for a single SVG—with the current architecture of SVGO, I don't see this being practical. Most plugins depend on the previous plugin having concluded or previous nodes having been processed already.

You may want to peek at https://github.com/svg/svgo/issues/1769 which seems more relevant.

**Comment by emansom** [comment]
> Then, yes I'm aware of worker threads. However, this issue is regarding the use of multiple cores for a **_single_** SVG, not across multiple SVGs.

The plugins could be run concurrently via worker pool, the resulting SVG then [merged](https://en.wikipedia.org/wiki/MapReduce). Kind of like multi-pass, but different. Would require some re-architecture, yes.

> My comment was not referring to a technical limitation in hardware or Node.js, but rather an architecture limitation with how SVGO processes SVGs.

"It's currently not possible to use multiple cores in any capacity."
Which is [wrong](https://youtu.be/kXJBNfBwtEA).

**Update**: to eleborate further, this was/is a feature request, stating things like "not possible in any capacity currently" is obvious, that's why the feature request was made! Thus it comes off more as a remark on how it is entirely impossible to implement ever, and therefore does not make sense; which is wrong and a incorrect assumption to make.

Four years of dismissal and not giving it a second thought, SVGO could've been running at lightning speed now.

> Processing multiple SVGs in parallel would be simple enough to do. As for taking advantage of multiple cores for a single SVG—with the current architecture of SVGO, I don't see this being practical. Most plugins depend on the previous plugin having concluded or previous nodes having been processed already.

For small SVGs the overhead would not be worth it, agreed. For very very large SVGs however, it could be beneficial.

**Comment by SethFalco** [comment]
You're not really adding anything meaningful to the conversation, and clearly haven't read the issue properly.

The original issue asked a question, which was answered accurately. What you claim was obvious clearly wasn't—considering the original issue was a question about it.

My statements following also made clear that we'd be open to proposals so we could get this support. If your interpretation is that I therefore implied it's impossible to implement, that's on you. My comment says nothing like that.

If you'd like to submit a PR, it's very welcome! But less drivel please.
