### ISSUE TITLE
Cannot find module 'csso' or its corresponding type declarations

### ISSUE THREAD

**Issue by daniluk4000** [svg/svgo#1708]
**Describe the bug**
![изображение](https://user-images.githubusercontent.com/10450717/201334827-6c6de9ce-0b4e-4095-a5d4-a1ba6b2c9fab.png)

**To Reproduce**
Install version 3.0.1

**Expected behavior**
csso types are included in dependencies or error desn't happen

**Desktop (please complete the following information):**
 - SVGO Version 3.0.1
 - NodeJs Version 16.18.1
 - OS: Windows 11

**Comment by TrySound** [comment]
Adding types dependencies for non-ts users bloats node_modules. I recommend you to add `@types/csso` in your project.

**Comment by daniluk4000** [comment]
@TrySound shouldn't this be included in readme, as more and more users use TS now?

**Comment by TrySound** [comment]
Would you like to make a PR?

**Comment by daniluk4000** [comment]
Sure

**Comment by dumbmatter** [comment]
> Adding types dependencies for non-ts users bloats node_modules. I recommend you to add `@types/csso` in your project.

Then why does svgo include types, rather than putting them in a separate @types/svgo package? Seems it make sense to either include all the types or none of them. Very uncommon for packages to include types but also require you to install @types packages for various transitive dependencies.

**Comment by TrySound** [comment]
Every second does it actually. Perhaps you are just lucky to not face it. We either bloat js users or give small headachss to ts users. Ideally of course just provide types on every package side.

**Comment by dumbmatter** [comment]
But if these are the options:

1. Include types for all transitive dependencies - most bloat, but easiest for TS users
2. Include no types in package, use @types/ for everything - least bloat, 2nd easiest for TS users
3. Include types, but error if no @types/ installed for transitive dependencies - 2nd most bloat, worst for TS users (error about unrelated package is more confusing than no types, since in my experience it basically never happens unless it's a bug or you did something wrong, although I guess I may be wrong)

...then it seems like option 3 is strictly the worst option. Option 2 is less bloat and less confusing for TS users. So why add bloat just to make it more confusing? Unless you want to add enough bloat to make it less confusing.

Just my 2 cents, I don't mean to derail into bikeshedding, I will refrain from further comments on this issue :)

**Comment by valleywood** [comment]
> > We either bloat js users
> 
> I might be missing something; what would get bloated? My understanding is that `@types/*` packages have no impact on either builds nor runtime Node.js. I think @dumbmatter’s suggestion for #1 would be the simplest fix and I’m not sure what would be bloated.

I agree and adding types to my project using `yarn add --dev @types/csso` would actually give me issues (which of course can be handled) with running `yarn depcheck` which would point out ` @types/csso`ad an unused devDependency although my tsc build would fail without it.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v3.0.2
