### ISSUE TITLE
optimized svg removes rotate transform

### ISSUE THREAD

**Issue by MoritzLoewenstein** [svg/svgo#1734]
**Describe the bug**
The transform rotate(180deg) is removed on the optimized svg.

**To Reproduce**
1. Optimize chevron.svg (attached) without any options
2. Compare the orientation of the optimized (attached as chevron_out.svg) and the original svg

**Expected behavior**
The optimized svg is not rotated.

**Screenshots**

**Desktop (please complete the following information):**
 - SVGO Version 3.0.2
 - NodeJs Version 18.12.1
 - OS: Win 10
 
**Additional context**
![chevron](https://user-images.githubusercontent.com/32882329/210963580-f14e80de-365d-4bbb-8bae-bf9dac905a82.svg)
![chevron_out](https://user-images.githubusercontent.com/32882329/210963609-ad9f9757-c73c-44b5-8c02-644d35be28bb.svg)

Edit: This seems to be caused by convertPathData and/or convertTransform, if one or both of these plugins is active the rotation will not be applied. I will try to further debug this and possibly submit a pr.

**Comment by MoritzLoewenstein** [comment]
They are as images under "Add any other context about the problem here.", and I attached them in the zip file.
[files.zip](https://github.com/svg/svgo/files/10361421/files.zip) @JoKalliauer

**Comment by JoKalliauer** [comment]
@MoritzLoewenstein: You wrote it the wrong way round `rotate(180deg)` is replaced by `rotate(180)`, however it should get removed because it is invalid.

I think treating `rotate(180deg)` as `rotate(180)` is reasonable, even though it might be invalid and should be removed, however I do not know the SVG1.1-Secifications that well.

**rotate(180deg)**
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 9">
  <path stroke="red" stroke-width="2.4" d="M0,0,6,6l6-6" transform="translate(12.849 7.697) rotate(180deg)"/>
</svg>
```
![rotate(180deg)](https://user-images.githubusercontent.com/15687581/211057008-d6cb3a89-91dc-4246-8c02-f06dd60efffe.svg)



**rotate(180)**
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 9">
  <path stroke="red" stroke-width="2.4" d="M0,0,6,6l6-6" transform="translate(12.849 7.697) rotate(180)"/>
</svg>
```
![rotate(180)](https://user-images.githubusercontent.com/15687581/211057156-574ac82e-4ab3-4c3c-b3f7-5ac2e5ae1915.svg)

**Conclusion**
I think this issue should be closed as invalid.

**Comment by MoritzLoewenstein** [comment]
I didnt know that rotate(180deg) is an invalid transform, my bad. Thanks for the help.
