### ISSUE TITLE
Use esbuild instead of rollup

### ISSUE THREAD

**Issue by LeoDog896** [svg/svgo#1739]
ESbuild is [magnitudes faster](https://esbuild.github.io/) for development than rollup, *but* requires the source package to be ESM. Converting to ESM, however, has been discussed in #1429. If a discussion does happen for using ESM modules, a separate issue should be raised.

There is a [workaround for using require](https://github.com/evanw/esbuild/issues/566#issuecomment-735551834) which *usually* works and can be implemented.

**Comment by SethFalco** [comment]
Hey! Thanks for the suggestion.

I'm closing this because while we could move to esbuild, there's no significant reason to. We're not having any problems with Rollup, it's still maintained, it's already working out great for bundling, etc.

We could always consider switching in future if any of that ever changes, but right now, it doesn't make sense to change it to address an issue that isn't affecting us.
