### ISSUE TITLE
Large SVG files

### ISSUE THREAD

**Issue by Voronchuk** [svg/svgo#177]
I have large file with about 44000 lines and 9.1mb in total size.

iMac:frontendEngine voronchuk$ svgo coolfarmers.svg 
iMac:frontendEngine voronchuk$ svgo coolfarmers.svg 

It just quits without any errors... any suggestions how to resolve that?

Small SVG files are converted without troubles.

**Comment by GreLI** [comment]
It would be helpful if you could provide such example files. Please, don't attach images to Github, since it doesn't support SVG.

**Comment by huantingchen** [comment]
Hi @GreLI 
I'm also struggling with large SVG files. Previously I used 0.5.0 which was able to handle my large SVG files (30-40MB) in 30-50 seconds. However, later versions (since 0.5.1) it would be just stuck there. It took too long to wait so I didn't see any error. On the other hand, the release notes of 0.5.1 is missing. Would you please point out what have been changed since 0.5.0?

**Comment by GreLI** [comment]
@huantingchen you can see the changelog for v0.5.1 in [CHANGELOG.md](https://github.com/svg/svgo/blob/master/CHANGELOG.md#---051--30032015). There was added a check for intersections in `mergePaths` plugin and since it has O(n·log(n)) complexity it could slow down the process. Try disabling it.

**Comment by huantingchen** [comment]
@GreLI Thanks for pointing it out. Just tried and it worked well.
