### ISSUE TITLE
Code optimizations that result in smaller SVGs downstream better off as minor version?

### ISSUE THREAD

**Issue by Volker-E** [svg/svgo#1871]
Hi all, 
thanks for the recent v3.0.4 and v3.0.5 updates, specifically @SethFalco. 

We at Wikimedia Foundation are big long-term fans of SVGO, see a.o. https://www.mediawiki.org/wiki/Manual:Coding_conventions/SVG and myself a task contributor for the repo.

One question that came up in discussions around some package updates, not pinning our versions strictly (aka "svgo": "^3.0.3") has resulted in updating to 3.0.5 in an unrelated patch and with that in a huge number of small changes to the icons: Wouldn't have those recent optimizations been better received downstream as minor version update, for example v3.1.0?

**Expected behavior**
No patch version should result in downstream major SVG output changes.

**Desktop (please complete the following information):**
 - SVGO Version 3.0.3 vs 3.0.5

**Comment by SethFalco** [comment]
Hey @Volker-E!

Valid point, this mostly comes down to what we interrupt as a minor change. I had opted to increment the patch version because everything that came through were either improvements to existing plugins, bug fixes, or refactors of existing plugins.

However, there was one new optimization that was introduced as part of an existing default plugin. That's likely what resulted in the changes in your files. In retrospect, I should've incremented minor instead, since it ultimately included a new default optimization:

* https://github.com/svg/svgo/pull/1822

Can I just confirm if you ran into any issues as a result of this?
(Beyond the unexpected work to vet the changes.)

Regardless, I'd be happy to favor minor over patch more. Sorry for the headache!

> No patch version should result in downstream major SVG output changes.

I'm not sure what the best way to define major is. However, whenever a new optimization is introduced, regardless of if it's a new or existing plugin, I will increment minor instead of patch in future.

---

As a side-note, while I understand this is about the semantics/expectations of what would change between versions, just adding a note in case you aren't aware. `^3.0.3` pins the major version only! So when running updates, that would've updated to 3.1.0 anyway. If you want to stay within the same minor version, you want `~3.0.3`… though that wouldn't have helped in this case. ^-^'
