### ISSUE TITLE
v4.0 rc - import plugin utils, e.g xast.js

### ISSUE THREAD

**Issue by vltansky** [svg/svgo#2030]
Hi, i tried to update to v4.0rc version, i have some custom plugins - i'm importing 
`import { querySelector, querySelectorAll } from 'svgo/lib/xast.js';`
couldn't find the way in 4.0rc to import it

**Comment by SethFalco** [comment]
Makes sense. I actually didn't export utilities on purpose to treat them as internal API only, but we can make a few exceptions for instances like these.

I'll look into it this week!

By any chance, is your project/plugin open-source or source-accessible? I'm writing draft PRs to help projects migrate to SVGO v4 which gives me more exposure to how it's used and what problems people may encounter. No problem if not, but it could be nice to have the context to help me decide if anything else needs to be adjusted. Otherwise, once v4.0.0-rc.1 is out, just let me know if you have any other issues. 👍🏽

**Comment by vltansky** [comment]
My project isn't open source, but I can share plugins with you privately for context if you are interested.
my mail vl.tansky@gmail.com
We also importing types like `XastElement, XastRoot, XastChild` from `svgo/lib/types` 
and `import _collections from 'svgo/plugins/_collections';`

i actually just migrated our plugins from svgo 2 to 3, so i'll be available during the 4 release candidates iterations so it will be easier for us to migrate :)

**Comment by SethFalco** [comment]
> My project isn't open source, but I can share plugins with you privately for context if you are interested

Normally I'm very open for users to share files with me, (SVGs, SVGO configs, or how they're using SVGO), but in this case we'll set it aside as I don't want me seeing the plugins to impact what I feel I can personally contribute to this repository, or the potential disputes if I ever implement similar ideas.

Thanks for offering, though! <3

> i'll be available during the 4 release candidates iterations so it will be easier for us to migrate :)

If you happen to notice any other objects/types from SVGO that you import, feel free to update me. Meanwhile, once v4.0.0-rc.1 is out (this weekend hopefully), you can also just say if you encounter any other problems.

**Comment by vltansky** [comment]
We actually would be happy to open source plugins, just most of them are very specific for our use cases.

**Comment by SethFalco** [comment]
Hey hey!

Sorry I took a while there. I had to set time aside from SVGO.

I've just released v4.0.0-rc.1 which exports `querySelector`, `querySelectorAll`, and `_collections`, as well as all type definitions. I did evaluate if there was anything else to export, but opted against doing so preemptively.

I'd like to keep the public interface of SVGO as small as possible. For v4, I'm more open to exporting things for ease of migration and due to lack of notice regarding deprecation. However, if we add anything else, there will certainly be a plan to deprecate them in future with ample notice and a clear migration path, then we can drop them in the next major release (v5) whenever that is. (Not planned anytime soon.)

We're going to take things slow, though.

Hit me with feedback if you encounter any other problems, but hopefully this fits your needs now!

**Comment by vltansky** [comment]
Hey, thanks for your work.
I succeeded to migrate all our plugins to RC1 🎉
I had to manually copy to our project: `visitSkip, visit, includesUrlReference`

**Comment by SethFalco** [comment]
Cool! Glad it's worked out then, and thank you for migrating the other internal methods on your side.

We'll leave the RC up for a while longer before making the official release in case any other issues come up. Unless there are other issues, I'd expect it to be the official release to be in October.
