### ISSUE TITLE
Scale SVGs to match precision

### ISSUE THREAD

**Issue by joeyhoer** [svg/svgo#293]
One possible optimization comes by scaling/multiplying each point by a power of 10 - matching the (most common ?) point of precision.

This could/would effect the width/height of the SVG, but it should still be equally useable in most situations.

**Example:**

Facebook logo (optimized 216 bytes - gzipped 197 bytes):

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8.2 17"><path d="M0 5.6h1.8V3.9c0-.8 0-1.9.6-2.6C2.9.5 3.7 0 5.1 0c2.2 0 3.2.3 3.2.3l-.5 2.6s-.7-.2-1.4-.2-1.3.3-1.3.9v2h2.8l-.2 2.6H5.1V17H1.8V8.2H0V5.6z"/></svg>
```

Facebook logo multiplied by 10 (optimized 191 bytes - gzipped 186 bytes):

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 82 170"><path d="M0 56h18V39c0-8 0-19 6-26C29 5 37 0 51 0c22 0 32 3 32 3l-5 26s-7-2-14-2-13 3-13 9v20h28l-2 26H51V170H18V82H0V56z"/></svg>
```

11.5% savings without gzip, 5.9% savings with gzip.

**Comment by littlefyr** [comment]
By simply truncating or rounding decimal points, there is an assumption about the user space in which the values are defined is both consistent within the document and already optimal. Its explicitly the value of SVG that this is not necessarily the case. 

As a result, the optimization is not likely to be optimal in many cases. Consider the following example from MDN:

```
<svg viewBox="0 0 120 120" version="1.1"
  xmlns="http://www.w3.org/2000/svg">
  <circle cx="60" cy="60" r="50"/>
</svg>
```
The optimization of this SVG should be:
```
<svg viewBox="0 0 12 12" version="1.1"
  xmlns="http://www.w3.org/2000/svg">
  <circle cx="6" cy="6" r="5"/>
</svg>
```
Ideally the concept of "precision" should be replaced with the concept of "maximum significant digits".

**Comment by GreLI** [comment]
Well, it's really rare when you meet such a file which have numbers ending with zeroes. Or have a GCD. Most likely you'll see an image with paths which contains Bezier curves with fractions in numbers (6 for each segment, sometimes 4). Moreover, rounding this numbers have considerable effect on image. E.g. rounding to one digit instead of two.

Also, you need to add ``viewBox`` attribute if an image didn't have it, to check if default values like ``stroke-width="1"`` used and add them too, appropriately scaled. Be sure that the profit will be more than the side effects. And so on.

**Comment by littlefyr** [comment]
The problem is that SVG is a mathematical construct. If you don't take that into account when processing SVG, you're going to break something. 

Here are non-trivial (ok only slightly non-trivial) SVG images using paths. I copied the first from MDN and modified it. Yes, I'm too lazy to do more than divide by 10, but you get the point. 

These image are, by definition, identical in every way except lexically (which I realize may not be the right word). However, the precision reducing algo will produce radically different results on each for the exact same parameters. 
```
<svg width="190px" height="160px" version="1.1" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 190 160">
  <path d="M11.2 11.2 C 21.2 21.2, 41.2 21.2, 51.2 11.2" stroke="black" stroke-width="2" fill="transparent"/>
  <path d="M71.2 11.2 C 71.2 21.2, 121.2 21.2, 121.2 11.2" stroke="black"  stroke-width="2" fill="transparent"/>
  <path d="M131.2 11.2 C 121.2 21.2, 181.2 21.2, 171.2 11.2" stroke="black"  stroke-width="2" fill="transparent"/>
  <path d="M11.2 61.2 C 21.2 81.2, 41.2 81.2, 51.2 61.2" stroke="black"  stroke-width="2" fill="transparent"/>
  <path d="M71.2 61.2 C 71.2 81.2, 111.2 81.2, 111.2 61.2" stroke="black"  stroke-width="2" fill="transparent"/>
  <path d="M131.2 61.2 C 121.2 81.2, 181.2 81.2, 171.2 61.2" stroke="black"  stroke-width="2" fill="transparent"/>
  <path d="M11.2 111.2 C 21.2 141.2, 41.2 141.2, 51.2 111.2" stroke="black"  stroke-width="2" fill="transparent"/>
  <path d="M71.2 111.2 C 71.2 141.2, 111.2 141.2, 111.2 111.2" stroke="black"  stroke-width="2" fill="transparent"/>
  <path d="M131.2 111.2 C 121.2 141.2, 181.2 141.2, 171.2 111.2" stroke="black"  stroke-width="2" fill="transparent"/>
</svg>
<svg width="190px" height="160px" version="1.1" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 .19 .16">
  <path d="M.0112 .0112 C .0212 .0212, .0412 .0212, .0512 .0112" stroke="black" stroke-width=".002" fill="transparent"/>
  <path d="M.0712 .0112 C .0712 .0212, .1212 .0212, .1212 .0112" stroke="black"  stroke-width=".002" fill="transparent"/>
  <path d="M.1312 .0112 C .1212 .0212, .1812 .0212, .1712 .0112" stroke="black"  stroke-width=".002" fill="transparent"/>
  <path d="M.0112 .0612 C .0212 .0812, .0412 .0812, .0512 .0612" stroke="black"  stroke-width=".002" fill="transparent"/>
  <path d="M.0712 .0612 C .0712 .0812, .1112 .0812, .1112 .0612" stroke="black"  stroke-width=".002" fill="transparent"/>
  <path d="M.1312 .0612 C .1212 .0812, .1812 .0812, .1712 .0612" stroke="black"  stroke-width=".002" fill="transparent"/>
  <path d="M.0112 .1112 C .0212 .1412, .0412 .1412, .0512 .1112" stroke="black"  stroke-width=".002" fill="transparent"/>
  <path d="M.0712 .1112 C .0712 .1412, .1112 .1412, .1112 .1112" stroke="black"  stroke-width=".002" fill="transparent"/>
  <path d="M.1312 .1112 C .1212 .1412, .1812 .1412, .1712 .1112" stroke="black"  stroke-width=".002" fill="transparent"/>
</svg>
```

It strikes me as definitely wrong that rounding to 1 decimal place would result in two totally different results for two identical images. Not in terms of filesize, but the images could not longer be said to be identical. 

Now i could have chosen to do more complex math and set the viewbox to ```0 0 10 10``` but who wants to do that? The point, I think, is clear.

That one might get a 4-6 decimal points from a drawing program has little bearing on the precision of those curve points. 4-6 decimal points on an image that has a total dimension of 10000x10000 is going to be a lot different than 4-6 decimal points on an image 10x10. 

The reason I think this is important is that without taking the math into account, you can't, for example, have a directory full of SVGs that you expect to compress well _unless you enforce that they're all created identically_ which is going to be impossible unless you are also the source of all those SVGs. 

I get that this is hard. But because it breaks some fundamental properties of SVG, you either have to account for it or clearly outline the limitations.

**Comment by joeyhoer** [comment]
@littlefyr I do like your point of "maximum significant digits", but as @GreLI pointed out, a GCD is very infrequent in most realistic applications.

I'm having some difficulty understanding the relevance of your comments as it pertains to this particular feature request. While I understand and agree that modifying the is a delicate procedure, and that extra care must be taken to ensure that all values are scaled equally, neither of your examples appear to demonstrate the optimal markup using the suggested transformation, which would be:

```
<svg width="190px" height="160px" version="1.1" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 1900 1600">
  <path d="M112 112 C 212 212, 412 212, 512 112" stroke="black" stroke-width="20" fill="transparent"/>
  <path d="M712 112 C 712 212, 1212 212, 1212 112" stroke="black"  stroke-width="20" fill="transparent"/>
  <path d="M1312 112 C 1212 212, 1812 212, 1712 112" stroke="black"  stroke-width="20" fill="transparent"/>
  <path d="M112 612 C 212 812, 412 812, 512 612" stroke="black"  stroke-width="20" fill="transparent"/>
  <path d="M712 612 C 712 812, 1112 812, 1112 612" stroke="black"  stroke-width="20" fill="transparent"/>
  <path d="M1312 612 C 1212 812, 1812 812, 1712 612" stroke="black"  stroke-width="20" fill="transparent"/>
  <path d="M112 1112 C 212 1412, 412 1412, 512 1112" stroke="black"  stroke-width="20" fill="transparent"/>
  <path d="M712 1112 C 712 1412, 1112 1412, 1112 1112" stroke="black"  stroke-width="20" fill="transparent"/>
  <path d="M1312 1112 C 1212 1412, 1812 1412, 1712 1112" stroke="black"  stroke-width="20" fill="transparent"/>
</svg>
```

This is 5.5% smaller than the example using the tenths place and 10.7% smaller than the example using the ten thousandths place. When gzipped, thats 1.3% and 4.2% smaller, respectively.

Of course, there are further optimizations that could be applied to the given example, but I'm hoping the simplicity of your examples will further illustrate the point.

I think you may be confusing some other optimization (rounding?) with the optimization I am suggesting.

**Comment by paperboyo** [comment]
+1

I've successfully used this technique manually to optimise SVGs. See e.g. https://github.com/guardian/frontend/pull/5041#issuecomment-48520340 for (a bit muddled) explanation/example. Maybe SVGO could produce several differently scaled images and then choose the one that optimises to the smallest file?

Regards
m.

**Comment by littlefyr** [comment]
@joeyhoer I'm piggy backing on your issue because what I am suggesting is effectively the same. 

While its true, as @GreLI says, that you would need to have a viewBox in order to do that, the viewBox only defines the coordinate of the viewport. If no viewBox is defined, you can use ```viewbox="0 0 width height"```.

One way to do this is to divide by a sufficient power of 10 that makes all the values between 0 and 1 (ok +1 and -1) round the value, to say 6 decimal places, and multiply by 10^6 (in this case).

The biggest problems are (and I'm not sure its not a problem) may be with some path constructs like Arcs. I've never used them, but when I tried building one of my examples, i naively tried multiplying all the values by 10, but the arcs broke. 

Also using different units like mm or cm would be challenging.

**Comment by GreLI** [comment]
> The biggest problems are (and I'm not sure its not a problem) may be with some path constructs like Arcs. I've never used them, but when I tried building one of my examples, i naively tried multiplying all the values by 10, but the arcs broke.

Yeah, that's because three of 7 parameters there is rotation angle (often 0, but if present shouldn't be modified) and flags (0 or 1, spec says they can be set by any non-zero value, but no sense in doing so).

**Comment by philbar** [comment]
I'm not sure how to approach this mathematically, but we could also reduce file size by multiples of 2 and 5.

In the example from [Mar 19](#issuecomment-83773767) we could save an additional 8.8% by multiplying everything by 5 (which gets rid of all the .2s). We could do the same with multiples of 2 if there are a large number of .5s.

    <svg width="190px" height="160px" version="1.1" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 950 800">
    <path d="M56 56 C 106 106, 206 106, 256 56" stroke="black" stroke-width="10" fill="transparent"/>
      <path d="M356 56 C 356 106, 606 106, 606 56" stroke="black"  stroke-width="10" fill="transparent"/>
      <path d="M656 56 C 606 106, 906 106, 856 56" stroke="black"  stroke-width="10" fill="transparent"/>
      <path d="M56 306 C 106 406, 206 406, 256 306 " stroke="black"  stroke-width="10" fill="transparent"/>
      <path d="M356 306 C 356 406, 556 406, 556 306" stroke="black"  stroke-width="10" fill="transparent"/>
      <path d="M656 306 C 606 406, 906 406, 856 306" stroke="black"  stroke-width="10" fill="transparent"/>
      <path d="M56 556 C 106 706, 206 706, 256 556" stroke="black"  stroke-width="10" fill="transparent"/>
      <path d="M356 556 C 356 706, 556 706, 556 556" stroke="black"  stroke-width="10" fill="transparent"/>
      <path d="M656 556 C 606 706, 906 706, 856 556" stroke="black"  stroke-width="10" fill="transparent"/>
    </svg>

**Comment by atk** [comment]
You already round to the third digit after the dot. So you can try to find the least common multiple of all node numbers (to a deviation of n% - that the user could specify) and multiply everything with that.

**Comment by keithclark** [comment]
I started working on something like this a while ago for a tool I was building. My approach was to scale out precision by raising values by a power of ten. I've created a plugin for SVGO and raised a work-in-progress [PR on my fork](https://github.com/keithclark/svgo/pull/1) if you'd like to take a look.

**Comment by littlefyr** [comment]
How about this. 

1. The user passes in the number of significant digits (`sd`). 
1. Get the rounding factor (bad term) `var rounding = Math.pow(10,sd);`
1. Get all the values to be scaled into an array (`allValues`). 
1. Get the absolute value of each value to be scaled: `var absValues = allValues.map( (v) => Math.abs(v));`
1. Get the minimum value and multiply by our rounding factor: `var scaling = Math.min.apply(null, absValues) * rounding;`
1. Scale our original values: `var newValues = allValues.map( (v) => Math.round(v / scaling));`
1. Find the greatest common divisor in `newValues` (use mathjs.org, or similar): `var gcd = math.gcd.apply(null, newValues);`
1. Scale all the values by the GCD: `if (gcd !=1) { newValues = newValues.map( (v) => v/gcd); }

Now I'm sceptical that you'd ever likely do that last step. Yet, i think there is another level of optimization here. 

If you _really_ wanted to go a step further, You could divide `newValues` by every prime number between 1 and 10<sup>`sd`</sup> (there are 168 for `sd=3`) and find the prime that leaves you with the most integer values. You can then find the GCD of those whole numbers and use that as your final scaling factor. 

Or something like that.

**Comment by GreLI** [comment]
There is an article about such an optimization: [Understanding and Manually Improving SVG Optimization](https://css-tricks.com/understanding-and-manually-improving-svg-optimization/). The key part is making decision about does the image breaks. I'm afraid that cannot be automated.

**Comment by collinanderson** [comment]
It would be great to at least have a "scale" option like #102 so we can at least manually play around with multiplying by 10 (or whatever) ourselves. It wouldn't be automatic, but with a little bit of peeking at the source we could try different scale options.
