### ISSUE TITLE
MIME type is text/plain

### ISSUE THREAD

**Issue by dangodev** [svg/svgo#306]
SVG files that initially have a MIME type of `image/svg+xml` become `text/plain` after being touched by SVGO. This kinda throws a bug in scripts I’ve written which need to access MIME type for various purposes such as base64 encoding for web.

**Comment by GreLI** [comment]
I guess it's not svgo issue, it's an OS responsible for this. Usually, ``.svg`` extension has ``image/svg+xml`` MIME type, so you should write svgo output with it.

**Comment by dangodev** [comment]
@GreLI I don’t really understand your comment; could you please explain?

I was saying that svgo changes the MIME types for SVGs on my machine with the `svgo` command. I don’t understand how this is an OS issue.

**Comment by GreLI** [comment]
I have no idea how a program can *change* MIME type a single file.

**Comment by dangodev** [comment]
![screen shot 2015-02-02 at 2 42 34 pm](https://cloud.githubusercontent.com/assets/1369770/6007649/cbd16ae6-aae9-11e4-9663-0b5e4b855840.png)

`logo.svg` is an SVG saved straight out of Illustrator.

**Comment by GreLI** [comment]
Ok, got it. I guess your OS follows linux way and makes a guess about MIME type by looking into the file content. Since svgo removes doctype and xml prolog, that checks no longer work. Try for example disabling ``removeDoctype`` plugin:
```
svgo --disable=removeDoctype
```
But if you want to have maximum compression (doctype is totally useless in all other cases and even [isn't recommended](http://www.w3.org/TR/SVG/intro#NamespaceAndDTDIdentifiers) in the spec itself) you'd prefer to change how MIME type detection works (e.g. by .svg extension) or amend scripts depending on it. Unfortunately, I can't help you with that.

**Comment by dangodev** [comment]
Ah—I understand now. I didn’t understand that MIME was a result of file contents, in this case the `<?xml ...>` doctype like you specified. I guess that makes sense—I can’t imagine where else the MIME would exist other than file contents, but that hadn’t occurred to me.

Might I suggest adding this as a line in the README? It might be useful to other users as well—I searched the README before making this issue and MIME didn’t appear.

**Comment by sateffen** [comment]
The issue with the mimetype is not a thing with other tools. If you use

    xdg-mime query filetype logo.svg

this should print "image/svg-xml", because this tool uses the mime-type database of your OS instead of the file content.

So depending on the tool, you should get the correct mime-type. This could confuse some people as well, if you tell them "the mime-type changes".

**Comment by dangodev** [comment]
Well, then.

Thank you for educating me and sorry for opening up a non-issue. :) (no, seriously—thank both of you guys!)

**Comment by GreLI** [comment]
I'm glad, it's been settled.

**Comment by PezCoder** [comment]
@dangodev How did you fix it finally ? This : `svgo --disable=removeDoctype` is not working for me but after adding that xml you mentioned manually it worked.
Would be handy if I can get the above command to word.

**Comment by dangodev** [comment]
@PezCoder I didn’t really “fix” it; I just stopped relying on MIME type because it’s dependent on the contents of the file. It’s metadata, and technically unnecessary which is why I guess SVGO removes it by default—it kind of exists to strip unnecessary metadata from the file to compress it. In other words, I’m now aware that MIME type is volatile and unpredictable based on a number of factors.

As for which SVGO flag keeps the MIME type metadata in the file, I can’t say. But for my purposes I just rely on file extension now rather than MIME type.
