### ISSUE TITLE
<use> is not clearing

### ISSUE THREAD

**Issue by onlymega** [svg/svgo#310]
If item is defined in <defs> but not used in <use> it must be removed.
In the example below <g id="shape2"> need to be removed because it is not used anywhere:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="128" height="128" viewBox="0 0 100 100">
<defs>
<g id="shape1">
<path
     d="m 100,47 0,-30.45 Q 100,9.7 95.15,4.85 90.3,0 83.45,0 L 16.55,0 Q 9.7,0 4.85,4.85 0,9.7 0,16.55 L 0,47 q 11.15,4.5 23.6,6.85 12.9,2.45 26.4,2.45 13.5,0 26.4,-2.45 Q 88.85,51.5 100,47 z"
     id="path3230" />
</g>
<g id="shape2">
<path
     d="m 95.15,84.1 q -4.85,4.85 -11.7,4.85 l -66.9,0 Q 9.7,88.95 4.85,84.1 0.22070313,79.470703 0,73.05 l 0,10.4 q 0,6.8 4.85,11.7 4.85,4.85 11.7,4.85 l 66.9,0 q 6.85,0 11.7,-4.85 0.4,-0.4 0.75,-0.75 1.85,-2.15 2.9,-4.55 1.2,-2.95 1.2,-6.4 l 0,-10.4 q -0.220703,6.420703 -4.85,11.05 z"
     id="path3215" style="fill:#f0a362" />
 </g>
</defs>
<use x="0" y="0" width="100" height="100" xlink:href="#shape1" />
</svg>
```

**Comment by GreLI** [comment]
There is no such a plugin in ``svgo`` for now. Also, one may have an [icon system](http://tympanus.net/codrops/2013/11/27/svg-icons-ftw/) with source file inlined in html and then icons used within that html code later.
Perhaps the easiest way to implement it is to extend ``cleanupIDs`` plugin by removing the whole unused element in ``<defs>`` instead of just an ``id`` attribute.

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the new plugin has been just published.
