### ISSUE TITLE
Please put the plugin names in the docs for reference?

### ISSUE THREAD

**Issue by baloneysandwiches** [svg/svgo#327]
Since the user needs the exact plugin names to enable/disable at the CLI, wouldn't it be nice to have those as text in the docs? :neckbeard:

**Comment by sateffen** [comment]
You can see all plugin-names in the config file: [.svgo.yml](https://github.com/svg/svgo/blob/master/.svgo.yml) 

Otherwise one could argue that this:

* [ [>](https://github.com/svg/svgo/blob/master/plugins/cleanupAttrs.js) ] cleanup attributes from newlines, trailing and repeating spaces

could turn into this

* [ [cleanupAttrs](https://github.com/svg/svgo/blob/master/plugins/cleanupAttrs.js) ] cleanup attributes from newlines, trailing and repeating spaces

So it contains the name itself with a description. Do you think this would help?

**Comment by baloneysandwiches** [comment]
Right, but the YML doesn't tell what each plugin actually does. I like your formatting suggestion. That's what I had in mind. The single closing bracket as a link is pretty rough stuff. People want to be able to scan the docs quickly.

**Comment by jrunning** [comment]
+1

In addition to documenting the available plugins, it would be helpful if each of their configuration options was documented. At present it's not at all easy to figure out what a plugin does and what options are available for it.
