### ISSUE TITLE
Image loss when using svgo 

### ISSUE THREAD

**Issue by bbjunaid** [svg/svgo#378]
I have version 0.5.2. I used the svgo command with different variations of --multipass, --disable=removeUselessStrokeAndFill, --disable=convertPathData but none of them worked for me and I got image loss in all cases.

Before:
![screen shot 2015-06-04 at 4 00 26 pm](https://cloud.githubusercontent.com/assets/1175122/7996585/95374698-0ad6-11e5-9544-5a55194d20a0.png)

After: The BO in box is removed
![screen shot 2015-06-04 at 4 28 08 pm](https://cloud.githubusercontent.com/assets/1175122/7996588/9df0df24-0ad6-11e5-8d5c-de87426c9f05.png)

Here is the original file:
https://drive.google.com/file/d/0B8l8dIuxBRvKR3BBRzdiN3lJTUU/view?usp=sharing

**Comment by GreLI** [comment]
Well, the problem is triggered by `cleanupIDs`, but the file is illegal–it uses same id several times, and one of it is empty.

**Comment by pierrei** [comment]
Thanks for figuring out what the problem was! This file was generated automatically by Sketch and obviously can be rendered properly even though it has errors. To me this means `cleanupIDs` should be improved to handle this case to not silently remove stuff that actually renders okay. Maybe svgo could run a SVG validation on the input file and warn the user if the file is violating SVG standards? Right now we had no idea this was the case when running the tool :/

**Comment by GreLI** [comment]
Well, then it's a bug of Sketch in the first place. Report there for start.

**Comment by GreLI** [comment]
[v0.5.3](/svg/svgo/releases/tag/v0.5.3) with the fix has been just released.
