### ISSUE TITLE
Plugin to move gradients to <defs>?

### ISSUE THREAD

**Issue by Jakobud** [svg/svgo#403]
Programs like Illustrator never export SVGs with elemets like `<linearGradient>` within a `<defs>` tag. It's not a requirement according to the spec, but along the lines of SVG sprites used in HTML, there are situations where gradients have to be defined in a `<defs>` instead of in a `<g>` or `<symbol>`. Is there a plugin to do this automatically? Would it be hard to make one?

**Comment by GreLI** [comment]
No, there is no such a plugin I'm aware of. But the requirement is strange. The only purpose of `defs` is to prevent rendering reference elements. It's perfectly safe to use non-rendering elements like `linearGradient` without `defs`. Also, you can refer to other elements that aren't in `defs` as well.

Images can be even optimized in a such way, because you anyway using those elements somewhere, right? So, no, there is no such a plugin. Of couse, you can write it's by yourself, but currently there is no good API to moving elements around, just adding it to one content and removing from the old one.

**Comment by Jakobud** [comment]
I will dig up an example of the situation I'm referring to and get back to you.
