### ISSUE TITLE
Precision conceputally flawed

### ISSUE THREAD

**Issue by nathanuphoff** [svg/svgo#422]
The precision option currently sets the number of digits in the fractional part, as this is an obvious choice - you end up with less characters - yet it’s a rather dumbed down version of what the name suggests. Precision should account for the amount of increments per point/pixel. 

An example, 8.68285322 will currently cut off numbers until the preference is matched and will probably round the last fraction to preserve optical integrity. What would make more sense is divide a point and snap the fractional part to it’s nearest neighbor:

-p 1 rounds to 1/1 (.0) points, the example becomes 9
-p 2 rounds to 1/2 (.5) points, the example becomes 8.5
-p 3 rounds to 1/3 a third of (.333) points, the example becomes 8.666

Etcetera:
-p 4 becomes 8.75
-p 5 becomes 8.8
-p 6 becomes 8.666
-p 7 becomes 8.714
-p 8 becomes 8.625
-p 9 becomes 8.666
-p 10 becomes 8.7

This works both in terms of precision and in terms of saving bandwidth, the fraction would never have to rise above 3 fraction digits. The values for this preference remain the same, so no additional effort there. 

Feedback is welcome.

**Comment by GreLI** [comment]
Every digit after a point adds a byte, that's why setting of number of digits influences the file size significally. Considering web graphics, 3 digits is enough almost every time, often it can be reduced to 2 or even 1 digit, but that's requires handling (svgo doesn't know how do one uses an image).

But for transformations, 3 digits is not enough due to fact their are being multiplied, so there is separate property which defaults to 5.

I don't see any sense in rounding to 1/3. It makes quality worse and brings nothing about optimizing. The only approach I may think of: multiply SVG units with corresponding ajust of `viewBox` to get rid of fraction parts. But in such a case one can just scale content and only then perfom rounding.

**Comment by nathanuphoff** [comment]
I see your point, I guess it comes from just about any svg drawing application somehow getting their rounding messed up: whole points get values like 0.01245423. This off course has nothing to do with SVGO yet is annoying the life out of me all the same. Cheers.
