### ISSUE TITLE
Change the indentation to 2 instead of 4 for the --pretty.

### ISSUE THREAD

**Issue by lipis** [svg/svgo#424]
So it could be pretty and a bit smaller :) 2 is the new 4 anyway :dancer:

**Comment by nathanuphoff** [comment]
Thats why tabs where invented, so you can make the editor decide.

**Comment by lipis** [comment]
@nathanuphoff tabs were invented to save physical space.. something that is not applicable anymore.. tabs should die :)

**Comment by lipis** [comment]
http://blog.codinghorror.com/death-to-the-space-infidels/

**Comment by nathanuphoff** [comment]
@lipis Tabs have the advantage that every developer can set their preferred tab width and they’re done with it. Spaces can’t do that, so you prefer two, and someone else wants four depicts exactly where spaces suck. You can argue over why two is better than four but with tabs you don’t need to. No arguing, no reformatting wars, no bullshit trivial shit and just code without forcing your amazing superior style on everyone.

here you go, an complimentary link: http://images6.fanpop.com/image/photos/35100000/Norman-leon-35112912-245-150.gif

**Comment by lipis** [comment]
@GreLI What's your stance on that one? Would it make sense if not by default, being able to pass an argument for it?

**Comment by GreLI** [comment]
I don't mind. It's not hard to do, PRs are always welcome ;-)>

**Comment by jaydenseric** [comment]
It would be really cool if SVGO would either accept an indentation CLI option for or default to respect the [`.editorconfig`](http://editorconfig.org) file, if present.

**Comment by lipis** [comment]
@jaydenseric Not sure why would SVGO even think about using or respect `.editorconfig`.. :confused: `.editorconfig` is for editor's configurations :) open the .svg in your editor and it will be respected..

**Comment by jaydenseric** [comment]
`.editorconfig` is a centralized place to set encoding and formatting for all text files, so that you don't have to manually configure all your tools separately for consistency. SVGO is editing the SVG files, it is an editor.

Often, I will open the `--pretty` optimized files in Atom to make manual edits. Problem is, Atom conveniently respects my established SVG formatting config but SVGO doesn't and the files end up inconsistent.

Another benefit to respecting the config, other members from the team can jump in and start optimizing without having to ask anyone about the formatting. I don't trust everyone to laboriously follow up SVGO optimizations with manual reformatting to conform to our standards.

**Comment by lipis** [comment]
I know exactly what editorconfig is.. but last time I checked SVGO is not editor.. it's a command line tool..

**Comment by vaughandroid** [comment]
@jaydenseric I for one would be really confused if SVGO behaved differently on different machines, depending on editorconfig settings.

This whole issue seems a bit pointless anyway. Can't you just run the outputted files through a prettifier with settings for your team?

**Comment by GreLI** [comment]
You can change it with `--indent 2` option since v0.6.4.

**Comment by lipis** [comment]
:+1:

**Comment by lipis** [comment]
Thank you for that! https://github.com/lipis/flag-icon-css/pull/220
