### ISSUE TITLE
Odd stroke effect on path completion

### ISSUE THREAD

**Issue by nolanlawson** [svg/svgo#481]
SVGO v0.6.1 fails to completely draw this box-shaped path - note the missing piece in the upper-left corner.

![screenshot 2016-01-07 19 11 46](https://cloud.githubusercontent.com/assets/283842/12186648/dd609b76-b572-11e5-9a7d-60b2def1f8ee.png)

SVGs to reproduce:

Input:

``` svg
<svg width="350" height="350" viewBox="0 0 350 350" xmlns="http://www.w3.org/2000/svg"><title>Slice 1</title><g stroke-width="9" stroke="#231F20" fill="none" fill-rule="evenodd"><path d="M130.395265,74.1325086 L337.114778,74.1325086 L337.114778,238.132509 L307.700143,238.132509 L307.700143,287.332509 L258.675753,238.132509 L130.395265,238.132509 L130.395265,74.1325086 Z"/></g></svg>
```

(Incorrect) output:

``` svg
<svg width="350" height="350" viewBox="0 0 350 350" xmlns="http://www.w3.org/2000/svg"><title>Slice 1</title><path d="M130.395 74.133h206.72v164H307.7v49.2l-49.024-49.2h-128.28v-164z" stroke-width="9" stroke="#231F20" fill="none" fill-rule="evenodd"/></svg>
```

(Manually) corrected output:

``` svg
<svg width="350" height="350" viewBox="0 0 350 350" xmlns="http://www.w3.org/2000/svg"><title>Slice 1</title><path d="M130.395 74.133h206.72v164H307.7v49.2l-49.024-49.2h-128.28v-168.5z" stroke-width="9" stroke="#231F20" fill="none" fill-rule="evenodd"/></svg>
```

I simply ran `svgo` from the command line, no extra options.

(Note that in the corrected version, I changed `164z` to `168.5z`.)

**Comment by GreLI** [comment]
That's interesting case, because, if you remove `v-164` (`z` will do the job) or replace it with `L130.395 74.133` (like the first `M`)–then it would be like the original one. However, the relative `lineto` command gives such a result. It seems that it's a particularity (or even a bug) of an edge case of stroke drawing.

I don't have a solution for this except removing that last line segment which would be completed by `z` anyway. But there are cases when a path ends not with a straight line.

**Comment by nolanlawson** [comment]
Interesting; just thought I would let you know. :) It's not too hard to manually correct.
