### ISSUE TITLE
removeUselessStrokeAndFill plugin doesn't remove invisible paths

### ISSUE THREAD

**Issue by caub** [svg/svgo#638]
I have this config:
```js
{multipass:true, floatPrecision:2, plugins: [
	{mergePaths: false}, 
	{convertShapeToPath: false}, 
	{removeUselessStrokeAndFill: true}
]}
```
shouldn't this clean an invisible path like: 
`<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.41"><path fill="none" d="M-107.52-76.8h407.25V32.84h-407.25z"/></svg>`

It doesn't

**Comment by elrumordelaluz** [comment]
@caub the fact that there is a `<path>` with attribute `fill` with the value `none` doesn't means is useless, since `fill=none` is useful to show the `stroke` and so on.
I think because of this, the author (@deepsweet) checks if there is an attribute `fill` but with value different than `none` [here](https://github.com/svg/svgo/blob/master/plugins/removeUselessStrokeAndFill.js#L38)

**Comment by caub** [comment]
ok, thanks
