### ISSUE TITLE
Recommended plugins for lossless optimization

### ISSUE THREAD

**Issue by pornel** [svg/svgo#646]
I'm adding SVGO to [ImageOptim](https://github.com/ImageOptim/ImageOptim). https://github.com/ImageOptim/ImageOptim/blob/master/svgo/index.js

* Do you have a recommended set of plugins to use? 
* Are there any mutually-exclusive plugins? (I could run multiple optimizations in parallel with different settings to find the best approach for each file).
* Which plugins are safest to run? I'm worried that some changes could change how the image looks, or break scripts if SVG's DOM is manipulated by JS.

**Comment by GreLI** [comment]
* Generally, I recommend all enabled by default plugins. However, some plugins like `removeTitle` are currently disabled by default because of some considerations, which I think is not the preferrable choice of most users. I'm planning to enable them, but after some rearranging of things. Also, `mergePaths` has O(n·log(n)) complexity (against number of points in paths) which is slow for large pictures (like many megabytes).
* `removeViewBox` and `removeDimensions` are somewhat exclusive, one most likely will not want to run both at the same time. Both they are disabled by default. Also there are some image manipulation plugins which are not recommended to run unless you know what you're doing.
*  `cleanupAttrs`, `removeDoctype`, `removeXMLProcInst`, `removeComments`, `removeMetadata`, `removeTitle`, `removeDesc`,  ` removeEditorsNSData`, `removeEmptyAttrs`, `removeHiddenElems`, `removeEmptyText`, `removeEmptyContainers`, `convertStyleToAttrs`, `convertColors`, `removeNonInheritableGroupAttrs`, `cleanupNumericValues`, `cleanupListOfValues`, `moveElemsAttrsToGroup`, `collapseGroups` are quite safe, until styles or JS is relied on something removed or changed (which can be everything). Regarding some other plugins:
	* `removeUselessDefs` is good in removing non-used (hidden) parts, but it may destroy images like sprites or icon libraries where everything is hidden.
	* `minifyStyles` minifies CSS in SVG, depends on CSSO. Should be fine, but can't guarantee. (SVGO by itself can't parse CSS.)
	* `convertPathData` is the path processing plugin, applies transforms and optimizes path data. However, it's rounds the values and sometimes it may produce a notable change, especially with low precision. One should balance through size and quality.
	* `convertTransform` manipulates transforms and rounds values, which can also can be notable due to nature of transformations.
	* `removeUnknownsAndDefaults` is good in removing defaults, but JS or third-party may rely on it. Also, can be unsafe since SVGO don't understand CSS styles (SVGO processes only `style` attributes).
	* Same for `removeUselessStrokeAndFill`.
	* `removeUnusedNS` generally should be fine, but can remove `xlink` namespace if there is no `xlink:href` attribute while JS can rely on that.
	* `cleanupIDs` removes unused and minifies used IDs, which is unsafe in case of external CSS or JS. It checks for presence of `<script>` and `<style>` inside the SVG.
	* `moveGroupAttrsToElems` is a naive approach to pass transforms to children elements which is useful for later run of `convertPathData` and `collapseGroups`, but pretty useless without `convertPathData` applying transformations.
	* `convertShapeToPath` converts `polygon` and `polyline` to `path` but may break the image due to styles or JS.

Some plugins have additional settings, e.g. you can turn off minifying IDs in `cleanupIDs` or don't apply transformations in `convertPathData`.

**Comment by pornel** [comment]
That's very helpful. Thank you.

**Comment by GreLI** [comment]
You're welcome.
