### ISSUE TITLE
Replace circular paths with <circle>'s

### ISSUE THREAD

**Issue by premasagar** [svg/svgo#65]
When exported as SVG, Illustrator expresses circles as full-blown paths. These paths could be more succinctly expressed as simple `<circle>` elements.

**Comment by konclave** [comment]
+1

**Comment by GreLI** [comment]
Actually, you can note that the path segment like ``a5,5 0 1,0 10,0 5,5 0 1,0-10,0`` has shorter length then ``<circle cx="10" cy="10" r="5"/>``. So, there is no profit in making it circle. Moreover, you can make it even shorter without notable difference in a way like ``a5,5 0 1,0 .1,0``

**Comment by johan** [comment]
Strange apples and oranges comparison.

```
<path d="a5,5 0 1,0 10,0 5,5 0 1,0-10,0"/>
<circle cx="10" cy="10" r="5"/>
<path d="a5,5 0 1,0 .1,0"/>
```

Size isn't the only metric by which this cleanup is useful, though; if you want to hand edit the file to tweak things, a `<circle>` is orders of magnitude more hackable than the arc syntax.

**Comment by GreLI** [comment]
Well, it's unlikely that you'll find ‘arcto’ (‘a’) command in the wild. More likely that you find arcs within complex paths (that's why I compare only the command) expressed with bezier curves which are written with 6 coordinates pairs. Converting these curves to arcs gives much more, especially when one arc is expressed with few curves.
I have a [prototype](https://github.com/GreLI/svgo/tree/arcs) of such an optimization, but it's imperfect (rounding errors make effect) and a little bit outdated. (Also, beware of force pushes.) Currently, I'm buzy with fixing main bugs of svgo to ensure its correct work, and I've almost finished with it.

**Comment by waldyrious** [comment]
> if you want to hand edit the file to tweak things, a <circle> is orders of magnitude more hackable
:+1: I'd prefer the circle markup too, or at least have that as an option.

**Comment by GreLI** [comment]
FYI version 0.6 of svgo recognizes arcs in curves and converts them correspondingly. Arcs path commands like `a5.07 5.07 0 1 0-2.8-9.72 5.07 5.07 0 0 0 2.8 9.72` (with precision=2) in your example are shorter as an part of an path then a separate `<circle>`.
