### ISSUE TITLE
Hoisting transform to group

### ISSUE THREAD

**Issue by drewnoakes** [svg/svgo#801]
I'm finding SVGO useful and would like to start contributing.

I found some output from the library resembling:

```xml
<g>
  <path transform="translate(123,456)" d="..."></path>
  <path transform="translate(123,456)" d="..."></path>
  ...
</g>
```

Is it safe in general to hoist identical transforms to the parent group?

```xml
<g transform="translate(123,456)">
  <path d="..."></path>
  <path d="..."></path>
  ...
</g>
```

I could find no discussion about this on the issue tracker.

**Comment by GreLI** [comment]
Yes, the reason is because paths are being processed by `convertPathData` by default, which applies transforms to paths. However, it doesn't apply always, some factors may prevent this—like having clipPath, or having stroke when transformation is non-uniform (we can't have distorted strokes in SVG). Unfortunately, there is no complicated logic to check for such factors.

Also, transforms doesn't apply to simple shapes (but some of them are converted to paths by `convertShapeToPath`), and there are requests like #594 to apply them, so it may be a good place to start.

**Comment by drewnoakes** [comment]
Thanks for the insights. I'll take a look at the linked issue as well.

**Comment by drewnoakes** [comment]
Was this fixed?

**Comment by TrySound** [comment]
Should be already the thing with `moveElemsAttrsToGroup` plugin
