### ISSUE TITLE
Access defaults.plugins only if property exists.

### ISSUE THREAD

**Issue by optunetobi** [svg/svgo#852]
https://github.com/svg/svgo/blob/1a3c32bb43f5382cb15148dc3b4e94ecb57938dc/lib/svgo/config.js#L30

**Comment by vcanales** [comment]
As far as I can tell, this check should probably live in the `preparePluginsArray` function if it's causing any trouble at all, otherwise the same thing that is causing problems at the moment, could come back. 

Also, the `Array.isArray({})` check being done previously should be good enough. Do you have an specific case where this fails?

**Comment by optunetobi** [comment]
@vcanales I had issues because of some external circumstances which removed/filtered files which the plugin should have used. These missing files led then to this error. Unfortunately I can't remember the exact problem or version of packages produced the issue. But I think it does no harm to have that check in there.
